name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install -g yarn
      - name: yarn install, build, and test
        run: |
          yarn install --frozen-lockfile
          yarn run build
  gh-pages:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          build_dir: dist
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
